spring:
  application:
    name: finance-dashboard

  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.vezfipvjvisfpzullvmh
    password: FinanceBase@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: ZmluYW5jZS1kYXNoYm9hcmQtc2VjcmV0LWtleS1mb3Itand0LXRva2VuLWdlbmVyYXRpb24tMjAyNA==
    expiration-ms: 86400000
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
